server:
  port: ${PORT:8080}
  servlet:
    context-path: /example-batch

spring:
  application:
    name: example-batch
  datasource:
    url: jdbc:postgresql://localhost:5432/batch_example
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: batch_example
        jdbc:
          batch_size: 5000
          batch_versioned_data: true
          lob:
            non_contextual_creation: true
        hibernate.types.print.banner: false
        order_inserts: true
        order_updates: true
        generate_statistics: true
    open-in-view: false

  batch:
    job:
      enabled: false
      chunk: 5000
    jdbc:
      initialize-schema: never
      table-prefix: batch_example.batch_
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
